default: &default  
    adapter: postgresql  
    encoding: unicode  
    pool: 5

development:  
    <<: *default  
    database: ror_development

test:  
    <<: *default  
    database: ror_test

production:  
    <<: *default  
    database: ror_production
    username: ror
    password: <%= ENV['TOYSWEET_DATABASE_PASSWORD'] %>